sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

before_script:
  - chmod +x gradlew
  
script:
  - ./gradlew check && ./gradlew dockerDistTar && docker build -t $DOCKER_ORGANIZATION/$DOCKER_REPO ./build/docker/

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_TEST_RESULT" == 0 ]; then 
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
      docker push $DOCKER_ORGANIZATION/$DOCKER_REPO;
    fi
  - bash <(curl -s https://codecov.io/bash) -t b4ecca35-ed02-4e87-9b34-fc8d814c2d5b
